// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	pageNames: {
		/**
		 * Bruhitch
		 */
		index: string
		/**
		 * Bruhitch › {0}
		 * @param {unknown} 0
		 */
		another: RequiredParams<'0'>
	}
	/**
	 * Authorization is required
	 */
	authorization: string
	/**
	 * Continue with Twitch
	 */
	continueWithTwitch: string
	settings: {
		/**
		 * Settings
		 */
		name: string
		/**
		 * Theme
		 */
		theme: string
		/**
		 * Dark
		 */
		darkTheme: string
		/**
		 * Light
		 */
		lightTheme: string
		/**
		 * Language
		 */
		language: string
		/**
		 * Delete account
		 */
		deleteAccount: string
		/**
		 * This action cannot be undone, are you sure?
		 */
		deleteAccountDescription: string
		/**
		 * Account deleted
		 */
		accountDeleted: string
		/**
		 * Account not deleted
		 */
		accountNotDeleted: string
		/**
		 * Refresh token
		 */
		refreshToken: string
		/**
		 * After this update your widget links. Just copy
		 */
		refreshTokenDescription: string
		/**
		 * Error on refresh token
		 */
		refreshError: string
		/**
		 * Token is Refreshed
		 */
		refreshSuccess: string
		/**
		 * Update your widget links
		 */
		refreshSuccessDescription: string
	}
	chat: {
		/**
		 * Chat
		 */
		name: string
		/**
		 * Chat widget link generator
		 */
		title: string
		/**
		 * Incorrect url
		 */
		incorrectUrl: string
		/**
		 * Chat preview
		 */
		preview: string
		/**
		 * Nickname
		 */
		nickname: string
		/**
		 * Channel
		 */
		channel: string
		/**
		 * Chat type
		 */
		chatType: string
		/**
		 * Default
		 */
		'default': string
		/**
		 * Block
		 */
		block: string
		/**
		 * Alternative block
		 */
		alternativeBlock: string
		/**
		 * Hide rewards
		 */
		hideRewards: string
		/**
		 * Hide claim channel points rewards in chat
		 */
		hideRewardsDescription: string
		/**
		 * Hidden nicknames
		 */
		hiddenNicknames: string
		/**
		 * Default color
		 */
		defaultColor: string
		/**
		 * Gradient only to custom nicknames
		 */
		gradientOnlyToCustomNicknames: string
		/**
		 * Custom color nicknames
		 */
		customColorNicknames: string
		/**
		 * Is gradient?
		 */
		isGradient: string
		/**
		 * Font
		 */
		font: string
		/**
		 * Font size
		 */
		fontSize: string
		/**
		 * Disable padding
		 */
		disablePadding: string
		/**
		 * Animation
		 */
		animation: string
		animationParams: {
			/**
			 * Animation parameters
			 */
			name: string
			/**
			 * duration in ms
			 */
			duration: string
			/**
			 * start scale
			 */
			startScale: string
			/**
			 * opacity
			 */
			opacity: string
		}
		/**
		 * Chat widget link
		 */
		chatLink: string
		/**
		 * Load config from link
		 */
		loadConfigFromLink: string
	}
	donationAlerts: {
		/**
		 * Donation alerts
		 */
		name: string
	}
	followAlerts: {
		/**
		 * Follow alerts
		 */
		name: string
		/**
		 * Follow alert settings
		 */
		title: string
		/**
		 * Follow alert preview
		 */
		preview: string
		/**
		 * Font
		 */
		font: string
		/**
		 * Font size
		 */
		fontSize: string
		/**
		 * Disable padding
		 */
		disablePadding: string
		/**
		 * Pattern
		 */
		pattern: string
		/**
		 * $username$ - show username. ![text](link) - image
		 */
		patternDescription: string
		/**
		 * Text color
		 */
		textColor: string
		/**
		 * Background color
		 */
		backgroundColor: string
		/**
		 * Background image
		 */
		backgroundImage: string
		/**
		 * Link to image
		 */
		backgroundImageDescription: string
		/**
		 * Nickname color
		 */
		colorNickname: string
		/**
		 * Is gradient nickname?
		 */
		isGradientNickname: string
		/**
		 * Vertical align
		 */
		verticalAlign: string
		/**
		 * Horizontal align
		 */
		horizontalAlign: string
		/**
		 * Top
		 */
		top: string
		/**
		 * Bottom
		 */
		bottom: string
		/**
		 * Center
		 */
		center: string
		/**
		 * Right
		 */
		right: string
		/**
		 * Left
		 */
		left: string
		/**
		 * Follow alert widget link
		 */
		widgetLink: string
	}
	subscribeAlerts: {
		/**
		 * Subscribe alerts
		 */
		name: string
	}
	raidAlerts: {
		/**
		 * Raid alerts
		 */
		name: string
	}
	bitsAlerts: {
		/**
		 * Bits alerts
		 */
		name: string
	}
	/**
	 * Copy
	 */
	copy: string
	/**
	 * Copied
	 */
	copied: string
	/**
	 * Load
	 */
	load: string
	/**
	 * Loaded
	 */
	loaded: string
	/**
	 * Add
	 */
	add: string
	/**
	 * Save
	 */
	save: string
	/**
	 * Saved
	 */
	saved: string
	/**
	 * Remove
	 */
	remove: string
	/**
	 * Delete
	 */
	'delete': string
	/**
	 * Cancel
	 */
	cancel: string
	/**
	 * Work In Progress
	 */
	wip: string
	/**
	 * An error has occurred
	 */
	errorOccurred: string
}

export type TranslationFunctions = {
	pageNames: {
		/**
		 * Bruhitch
		 */
		index: () => LocalizedString
		/**
		 * Bruhitch › {0}
		 */
		another: (arg0: unknown) => LocalizedString
	}
	/**
	 * Authorization is required
	 */
	authorization: () => LocalizedString
	/**
	 * Continue with Twitch
	 */
	continueWithTwitch: () => LocalizedString
	settings: {
		/**
		 * Settings
		 */
		name: () => LocalizedString
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Dark
		 */
		darkTheme: () => LocalizedString
		/**
		 * Light
		 */
		lightTheme: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Delete account
		 */
		deleteAccount: () => LocalizedString
		/**
		 * This action cannot be undone, are you sure?
		 */
		deleteAccountDescription: () => LocalizedString
		/**
		 * Account deleted
		 */
		accountDeleted: () => LocalizedString
		/**
		 * Account not deleted
		 */
		accountNotDeleted: () => LocalizedString
		/**
		 * Refresh token
		 */
		refreshToken: () => LocalizedString
		/**
		 * After this update your widget links. Just copy
		 */
		refreshTokenDescription: () => LocalizedString
		/**
		 * Error on refresh token
		 */
		refreshError: () => LocalizedString
		/**
		 * Token is Refreshed
		 */
		refreshSuccess: () => LocalizedString
		/**
		 * Update your widget links
		 */
		refreshSuccessDescription: () => LocalizedString
	}
	chat: {
		/**
		 * Chat
		 */
		name: () => LocalizedString
		/**
		 * Chat widget link generator
		 */
		title: () => LocalizedString
		/**
		 * Incorrect url
		 */
		incorrectUrl: () => LocalizedString
		/**
		 * Chat preview
		 */
		preview: () => LocalizedString
		/**
		 * Nickname
		 */
		nickname: () => LocalizedString
		/**
		 * Channel
		 */
		channel: () => LocalizedString
		/**
		 * Chat type
		 */
		chatType: () => LocalizedString
		/**
		 * Default
		 */
		'default': () => LocalizedString
		/**
		 * Block
		 */
		block: () => LocalizedString
		/**
		 * Alternative block
		 */
		alternativeBlock: () => LocalizedString
		/**
		 * Hide rewards
		 */
		hideRewards: () => LocalizedString
		/**
		 * Hide claim channel points rewards in chat
		 */
		hideRewardsDescription: () => LocalizedString
		/**
		 * Hidden nicknames
		 */
		hiddenNicknames: () => LocalizedString
		/**
		 * Default color
		 */
		defaultColor: () => LocalizedString
		/**
		 * Gradient only to custom nicknames
		 */
		gradientOnlyToCustomNicknames: () => LocalizedString
		/**
		 * Custom color nicknames
		 */
		customColorNicknames: () => LocalizedString
		/**
		 * Is gradient?
		 */
		isGradient: () => LocalizedString
		/**
		 * Font
		 */
		font: () => LocalizedString
		/**
		 * Font size
		 */
		fontSize: () => LocalizedString
		/**
		 * Disable padding
		 */
		disablePadding: () => LocalizedString
		/**
		 * Animation
		 */
		animation: () => LocalizedString
		animationParams: {
			/**
			 * Animation parameters
			 */
			name: () => LocalizedString
			/**
			 * duration in ms
			 */
			duration: () => LocalizedString
			/**
			 * start scale
			 */
			startScale: () => LocalizedString
			/**
			 * opacity
			 */
			opacity: () => LocalizedString
		}
		/**
		 * Chat widget link
		 */
		chatLink: () => LocalizedString
		/**
		 * Load config from link
		 */
		loadConfigFromLink: () => LocalizedString
	}
	donationAlerts: {
		/**
		 * Donation alerts
		 */
		name: () => LocalizedString
	}
	followAlerts: {
		/**
		 * Follow alerts
		 */
		name: () => LocalizedString
		/**
		 * Follow alert settings
		 */
		title: () => LocalizedString
		/**
		 * Follow alert preview
		 */
		preview: () => LocalizedString
		/**
		 * Font
		 */
		font: () => LocalizedString
		/**
		 * Font size
		 */
		fontSize: () => LocalizedString
		/**
		 * Disable padding
		 */
		disablePadding: () => LocalizedString
		/**
		 * Pattern
		 */
		pattern: () => LocalizedString
		/**
		 * $username$ - show username. ![text](link) - image
		 */
		patternDescription: () => LocalizedString
		/**
		 * Text color
		 */
		textColor: () => LocalizedString
		/**
		 * Background color
		 */
		backgroundColor: () => LocalizedString
		/**
		 * Background image
		 */
		backgroundImage: () => LocalizedString
		/**
		 * Link to image
		 */
		backgroundImageDescription: () => LocalizedString
		/**
		 * Nickname color
		 */
		colorNickname: () => LocalizedString
		/**
		 * Is gradient nickname?
		 */
		isGradientNickname: () => LocalizedString
		/**
		 * Vertical align
		 */
		verticalAlign: () => LocalizedString
		/**
		 * Horizontal align
		 */
		horizontalAlign: () => LocalizedString
		/**
		 * Top
		 */
		top: () => LocalizedString
		/**
		 * Bottom
		 */
		bottom: () => LocalizedString
		/**
		 * Center
		 */
		center: () => LocalizedString
		/**
		 * Right
		 */
		right: () => LocalizedString
		/**
		 * Left
		 */
		left: () => LocalizedString
		/**
		 * Follow alert widget link
		 */
		widgetLink: () => LocalizedString
	}
	subscribeAlerts: {
		/**
		 * Subscribe alerts
		 */
		name: () => LocalizedString
	}
	raidAlerts: {
		/**
		 * Raid alerts
		 */
		name: () => LocalizedString
	}
	bitsAlerts: {
		/**
		 * Bits alerts
		 */
		name: () => LocalizedString
	}
	/**
	 * Copy
	 */
	copy: () => LocalizedString
	/**
	 * Copied
	 */
	copied: () => LocalizedString
	/**
	 * Load
	 */
	load: () => LocalizedString
	/**
	 * Loaded
	 */
	loaded: () => LocalizedString
	/**
	 * Add
	 */
	add: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Saved
	 */
	saved: () => LocalizedString
	/**
	 * Remove
	 */
	remove: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Work In Progress
	 */
	wip: () => LocalizedString
	/**
	 * An error has occurred
	 */
	errorOccurred: () => LocalizedString
}

export type Formatters = {}
